#!/bin/bash

apt-get update

apt-get install -y \
  apt-transport-https \
  build-essential \
  ca-certificates \
  curl \
  fonts-noto \
  git \
  gnupg \
  grc \
  httpie \
  jq \
  libnss3-tools \
  unzip \
  wget \
  zip
